{% set name = "python-docker" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 72ac524c57b752a64ef42ebd43949859ffe3261179edc97b642e44e6558fb593

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pydantic
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - python_docker

about:
  home: https://github.com/costrouc/python-docker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Build docker images and interact with registries without docker
  description: |
    A pure python implementation to build docker images without docker
    and provide a python api for interacting with docker registries
  dev_url: https://github.com/costrouc/python-docker

extra:
  recipe-maintainers:
    - costrouc
